name: Python package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m venv venv
      - run: . venv/bin/activate
      - run: pip install --upgrade pip
      - run: pip install -e .[dev]
      - run: pytest --cov=src/data_doctor tests/
      - run: codecov
